# Generated by Django 4.2.4 on 2023-09-04 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='updated date'),
            preserve_default=False,
        ),
    ]
