# Generated by Django 4.2.4 on 2023-09-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_created_at_alter_user_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[('100 LEVEL', 'L100'), ('200 LEVEL', 'L200'), ('300 LEVEL', 'L300'), ('400 LEVEL', 'L400'), ('500 LEVEL', 'L500'), ('600 LEVEL', 'L600'), ('700 LEVEL', 'L700')], null=True, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='user',
            name='matric_no',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='matriculation number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_role',
            field=models.CharField(blank=True, choices=[('FACULTY PRESIDENT', 'Faculty President'), ('FACULTY GENERAL SECRETARY', 'Faculty General Secretary'), ('FACULTY TREASURER', 'Faculty Treasurer'), ('DEPARTMENT PRESIDENT', 'Department President'), ('DEPARTMENT GENERAL SECRETARY', 'Department General Secretary'), ('DEPARTMENT TREASURER', 'Department Treasurer'), ('GENERAL ADMIN', 'General Admin')], default='GENERAL ADMIN', max_length=100, verbose_name='user role'),
            preserve_default=False,
        ),
    ]
